# wrangler.toml
name = "dyez"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3456fbc02627470c920f51132c54a182" }
]
